# Generated by Django 6.0.7 on 2026-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('project_type', models.CharField(choices=[('graduation', 'Academic / Graduation Project'), ('commercial', 'Commercial / B2B Solution')], db_index=True, default='graduation', max_length=20)),
                ('client_name', models.CharField(help_text='University name or Client name', max_length=150)),
                ('country', models.CharField(default='Egypt', max_length=100)),
                ('summary', models.TextField(help_text='A brief short summary of the project.')),
                ('overview', models.TextField(help_text='Detailed overview of architecture and features.')),
                ('demo_video_url', models.URLField(blank=True, help_text='YouTube/Vimeo embed or MP4 video URL', null=True)),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverables included (e.g., source code, PDF, presentation)')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
