# Generated by Django 6.0.7 on 2026-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='رابط المعاينة المباشرة أو التجربة الحية للمشروع (Live Demo / Project URL)', null=True),
        ),
    ]
