# Generated by Django 6.0.7 on 2026-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, help_text='English Category Name', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name_en',
            field=models.CharField(blank=True, help_text='English Client name', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='country_en',
            field=models.CharField(blank=True, default='Egypt', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverables_en',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverables in English'),
        ),
        migrations.AddField(
            model_name='project',
            name='overview_en',
            field=models.TextField(blank=True, help_text='Detailed overview of architecture and features in English.'),
        ),
        migrations.AddField(
            model_name='project',
            name='summary_en',
            field=models.TextField(blank=True, help_text='A brief short summary of the project in English.'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, help_text='English Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverables in Arabic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=models.TextField(help_text='Detailed overview of architecture and features in Arabic.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='A brief short summary of the project in Arabic.'),
        ),
    ]
