# Generated by Django 6.0.7 on 2026-07-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Inquiries'), ('technical', 'Technical Details'), ('pricing', 'Pricing & Deliverables'), ('support', 'Support & Deployment')], db_index=True, default='general', max_length=30)),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Used to control order of items in list')),
            ],
            options={
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role_university', models.CharField(help_text='Role or University/Company name', max_length=200)),
                ('review_text', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo demo url from testimonial', null=True)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/avatars/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
