# Generated by Django 6.0.7 on 2026-07-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='video_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Official admin reply to this comment', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email for notification', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Approved to show publicly'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5),
        ),
    ]
