# Generated by Django 6.0.7 on 2026-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_testimonial_options_remove_testimonial_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم الكريم')),
                ('email', models.CharField(max_length=200, verbose_name='البريد أو رقم الهاتف')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع الاستفسار')),
                ('message', models.TextField(verbose_name='تفاصيل الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة والمتابعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة استفسار',
                'verbose_name_plural': 'رسائل واستفسارات التواصل',
                'ordering': ['-created_at'],
            },
        ),
    ]
