# Generated by Django 6.0.7 on 2026-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_site_url', models.URLField(blank=True, help_text='رابط موقع/منصة مشاريع التخرج المخصصة (مثال: https://academic-projects.com)', null=True)),
                ('academic_button_text', models.CharField(default='الانتقال لمنصة مشاريع التخرج الأكاديمية', help_text='نص الزر في مسار مشاريع التخرج', max_length=150)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع العامة',
            },
        ),
        migrations.CreateModel(
            name='StudioMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الإحصائية (مثال: مشروع بزنس و MVP مكتمل)', max_length=150)),
                ('value', models.CharField(help_text='القيمة الرقمية (مثال: +50 أو 100%)', max_length=50)),
                ('subtitle', models.CharField(blank=True, help_text='وصف مكمل (مثال: منصات سحابية وتطبيقات جوال حية)', max_length=200)),
                ('icon_name', models.CharField(default='rocket_launch', help_text='اسم أيقونة Material Symbols (مثل: rocket_launch, workspace_premium, public, code)', max_length=50)),
                ('color_theme', models.CharField(choices=[('primary', 'بنفسجي / Primary'), ('emerald', 'أخضر / Emerald'), ('secondary', 'أزرق / Secondary'), ('amber', 'ذهبي / Amber')], default='primary', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, help_text='إظهار في الصفحة الرئيسية')),
            ],
            options={
                'verbose_name': 'إحصائية الاستوديو',
                'verbose_name_plural': 'إحصائيات وإنجازات الاستوديو',
                'ordering': ['order', 'id'],
            },
        ),
    ]
