# Generated by Django 6.0.7 on 2026-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesetting_studiometric'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='academic_button_text_en',
            field=models.CharField(blank=True, default='Go to Academic Graduation Platform', max_length=150),
        ),
        migrations.AddField(
            model_name='studiometric',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='English metric subtitle', max_length=200),
        ),
        migrations.AddField(
            model_name='studiometric',
            name='title_en',
            field=models.CharField(blank=True, help_text='English metric title', max_length=150),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='admin_reply_en',
            field=models.TextField(blank=True, help_text='Official admin reply in English', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='review_text_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_university_en',
            field=models.CharField(blank=True, help_text='Role or University/Company name in English', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Official admin reply in Arabic', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role_university',
            field=models.CharField(help_text='Role or University/Company name in Arabic', max_length=200),
        ),
    ]
