# Generated by Django 6.0.7 on 2026-09-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
